// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGFDxHgM4yKIXjayZswFAuURAWYNb0ZuA',
    appId: '1:611853937212:web:3012b1b3c8d8cda8d6f139',
    messagingSenderId: '611853937212',
    projectId: 'tour-recommender-app',
    authDomain: 'tour-recommender-app.firebaseapp.com',
    storageBucket: 'tour-recommender-app.appspot.com',
    measurementId: 'G-6WNFWVGQJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAP-ln1Ij413GGNZuV-n3jVd190xZ638',
    appId: '1:611853937212:android:7d3377ffd18b19b5d6f139',
    messagingSenderId: '611853937212',
    projectId: 'tour-recommender-app',
    storageBucket: 'tour-recommender-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRiE0RnSm9adhOmv4gNWHnjISKHX36l4',
    appId: '1:611853937212:ios:e21f5fff12312b8bd6f139',
    messagingSenderId: '611853937212',
    projectId: 'tour-recommender-app',
    storageBucket: 'tour-recommender-app.appspot.com',
    iosBundleId: 'com.example.tourRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRiE0RnSm9adhOmv4gNWHnjISKHX36l4',
    appId: '1:611853937212:ios:e21f5fff12312b8bd6f139',
    messagingSenderId: '611853937212',
    projectId: 'tour-recommender-app',
    storageBucket: 'tour-recommender-app.appspot.com',
    iosBundleId: 'com.example.tourRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGFDxHgM4yKIXjayZswFAuURAWYNb0ZuA',
    appId: '1:611853937212:web:4e5bcc6cdf3943f3d6f139',
    messagingSenderId: '611853937212',
    projectId: 'tour-recommender-app',
    authDomain: 'tour-recommender-app.firebaseapp.com',
    storageBucket: 'tour-recommender-app.appspot.com',
    measurementId: 'G-1FVQS4NTFC',
  );
}
